Vsavritsky\MorpherBundle\Entity\Request:
    type: entity
    table: vsavritsky_morpher_request
    indexes:
        type_word_index:
            columns: [type, word]
        type_index:
            columns: [type]
        word_index:
             columns: [word]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
        word:
            type: string
        result:
            type: json_array